### ISSUE TITLE
关于服务端启动的配置

### ISSUE THREAD

**Issue by wcl2184** [airingursb/philosopher-back-end#2]
服务端启动需要单独配置极光推送服务，七牛，数据库之类的服务么？我好像没有看到数据库脚本之类的文件。另外如果我只想启动前端可以么

**Comment by airingursb** [comment]
@wcl2184 不需要数据库脚本，用的 sequelize，你只要建好同名的模式，数据表会自动生成的。其他配置详情请看 src/config/index.js 文件

**Comment by wcl2184** [comment]
好的，您这个项目已经不在运转了吗发自我的华为手机-------- 原始邮件 --------主题：Re: [airingursb/sophia-back-end] 关于服务端启动的配置 (#2)发件人：Airing 收件人：airingursb/sophia-back-end 抄送：wcl2184 ,Mention @wcl2184 不需要数据库脚本，用的 sequelize，你只要建好同名的模式，数据表会自动生成的。其他配置详情请看 src/config/index.js 文件
